[package]
name = "lywsd03mmc"
version = "0.1.1"
edition = "2024"
description = "Rust support for scanning and reading Xiaomi Mijia LYWSD03MMC BLE temperature and humidity sensors"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/v0y4g3r/lywsd03mmc"

[[bin]]
name = "read_lywsd03mmc"
path = "src/bin/read_lywsd03mmc.rs"

[dependencies]
btleplug = "0.12.0"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
futures = "0.3"
hex = "0.4"
log = "0.4"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt", "time"] }
uuid = "1"
